[project]
name = "thegarden"
version = "0.1.0"
description = "Simple database interaction tool for The Garden KuzuDB"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "kuzu>=0.0.8",
    "pytest>=8.0.0",
    "toml>=0.10.2",
]
