# Configuration file for hortalizas (vegetables) data
# This file defines the available vegetables/plants that can be grown in the garden

[metadata]
version = "1.0"
description = "Garden vegetables configuration"
last_updated = "2024-01-01"

# Hortalizas (Vegetables) definitions
[[hortalizas]]
id = 1
nombre = "Tomate"
descripcion = "Solanum lycopersicum - Hortaliza de fruto muy popular"
ciclo_dias = 120
siembra_mes_inicio = 9
siembra_mes_fin = 11
plagas_comunes = ["Trips", "Mosca blanca", "Pulgones", "Tizón tardío"]
cuidados = ["Riego regular", "Tutoreo", "Poda de brotes laterales", "Fertilización rica en potasio"]
tamano_promedio = 1.5
distancia_min = 0.6

[[hortalizas]]
id = 2
nombre = "Lechuga"
descripcion = "Lactuca sativa - Hortaliza de hoja de crecimiento rápido"
ciclo_dias = 60
siembra_mes_inicio = 3
siembra_mes_fin = 9
plagas_comunes = ["Caracoles", "Babosas", "Pulgones", "Mildiu"]
cuidados = ["Riego frecuente", "Sombra parcial en verano", "Cosecha escalonada"]
tamano_promedio = 0.3
distancia_min = 0.2

[[hortalizas]]
id = 3
nombre = "Zanahoria"
descripcion = "Daucus carota - Hortaliza de raíz rica en betacaroteno"
ciclo_dias = 90
siembra_mes_inicio = 8
siembra_mes_fin = 2
plagas_comunes = ["Mosca de la zanahoria", "Nematodos", "Gusano alambre"]
cuidados = ["Suelo suelto y profundo", "Raleo de plántulas", "Riego moderado"]
tamano_promedio = 0.1
distancia_min = 0.1

[[hortalizas]]
id = 4
nombre = "Pimiento"
descripcion = "Capsicum annuum - Hortaliza de fruto versátil"
ciclo_dias = 100
siembra_mes_inicio = 9
siembra_mes_fin = 11
plagas_comunes = ["Pulgones", "Trips", "Ácaros"]
cuidados = ["Riego moderado", "Tutoreo si necesario", "Protección del viento"]
tamano_promedio = 0.8
distancia_min = 0.4

[[hortalizas]]
id = 5
nombre = "Espinaca"
descripcion = "Spinacia oleracea - Hortaliza de hoja rica en hierro"
ciclo_dias = 45
siembra_mes_inicio = 3
siembra_mes_fin = 8
plagas_comunes = ["Minador de la hoja", "Pulgones"]
cuidados = ["Riego frecuente", "Sombra parcial en verano", "Cosecha temprana"]
tamano_promedio = 0.2
distancia_min = 0.15

# Garden structures (unusable areas)
[estructuras]
description = "Defines unusable areas in the garden as polygons"

[[estructuras.estructura]]
id = "structure_001"
nombre = "Casa de Herramientas"
tipo = "edificio"
descripcion = "Pequeña caseta para almacenar herramientas"
# Polygon coordinates (clockwise from top-left)
poligono = [
    [50.0, 50.0],   # top-left
    [150.0, 50.0],  # top-right
    [150.0, 120.0], # bottom-right
    [50.0, 120.0]   # bottom-left
]

[[estructuras.estructura]]
id = "structure_002"
nombre = "Camino Principal"
tipo = "camino"
descripcion = "Sendero de acceso principal al jardín"
# Path polygon
poligono = [
    [0.0, 280.0],
    [800.0, 280.0],
    [800.0, 320.0],
    [0.0, 320.0]
]

[[estructuras.estructura]]
id = "structure_003"
nombre = "Área Rocosa"
tipo = "obstáculo_natural"
descripcion = "Zona con muchas rocas, no apta para cultivo"
# Irregular polygon
poligono = [
    [600.0, 100.0],
    [720.0, 80.0],
    [750.0, 150.0],
    [680.0, 200.0],
    [620.0, 180.0]
]